language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - chmod 600 tests/Stubs/private.key
  - composer test

branches:
  only:
    - master
